import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  // Automatically generate sidebars based on folder structure
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generates the sidebar from the root `docs` folder
    },
  ],
};

export default sidebars;
